automation:
  - alias: Nastavit EcoVolter nabíječku
    id: ecovolter_set_charger_settings
    description: "Synchronizuje Home Assistant vstupy s nastavením nabíječky EcoVolter."
    trigger:
      - platform: state
        entity_id:
          - input_number.ecovolter_target_current
          - input_number.ecovolter_boost_time
          - input_number.ecovolter_kwh_price
          - input_number.ecovolter_boost_current
          - input_number.ecovolter_max_current
          - input_boolean.ecovolter_charging_enabled
          - input_boolean.ecovolter_three_phase_mode_enabled
          - input_boolean.ecovolter_boost_mode_enabled
          - input_boolean.ecovolter_local_panel_enabled
    action:
      - service: pyscript.set_ecovolter_setting
        data:
          target_current: "{{ states('input_number.ecovolter_target_current') | int }}"
          boost_time: "{{ states('input_number.ecovolter_boost_time') | int }}"
          kwh_price: "{{ states('input_number.ecovolter_kwh_price') | float }}"
          boost_current: "{{ states('input_number.ecovolter_boost_current') | int }}"
          max_current: "{{ states('input_number.ecovolter_max_current') | int }}"
          is_charging_enabled: "{{ is_state('input_boolean.ecovolter_charging_enabled', 'on') }}"
          is_three_phase_mode_enabled: "{{ is_state('input_boolean.ecovolter_three_phase_mode_enabled', 'on') }}"
          is_boost_mode_enabled: "{{ is_state('input_boolean.ecovolter_boost_mode_enabled', 'on') }}"
          is_local_panel_enabled: "{{ is_state('input_boolean.ecovolter_local_panel_enabled', 'on') }}"

  - alias: EcoVolter stav
    id: ecovolter_fetch_data_on_schedule
    description: "Pravidelně stahuje data ze zařízení EcoVolter."
    trigger:
      - platform: time_pattern
        minutes: "/2"
    condition: []
    action:
      - service: pyscript.fetch_ecovolter_data
    mode: single
